-- 用户表
CREATE TABLE IF NOT EXISTS t_user (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE COMMENT '用户名',
    email      VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
    phone      VARCHAR(20)  NOT NULL UNIQUE COMMENT '手机号',
    password   VARCHAR(100) NOT NULL COMMENT '密码',
    status     VARCHAR(20)  NOT NULL DEFAULT 'INACTIVE' COMMENT '用户状态',
    register_time TIMESTAMP   COMMENT '注册时间',
    last_active_time TIMESTAMP COMMENT '最后活跃时间',
    create_time TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

COMMENT ON TABLE t_user IS '用户表';
